// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateChoose: typeof import('./src/components/ThemeConfig/components/AnimateChoose.vue')['default']
    BasicForm: typeof import('./src/components/BasicForm/index.vue')['default']
    ColorChoose: typeof import('./src/components/ThemeConfig/components/ColorChoose.vue')['default']
    ControlItem: typeof import('./src/components/ThemeConfig/components/ControlItem.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    LockScreen: typeof import('./src/components/LockScreen/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepForm: typeof import('./src/components/StepForm/index.vue')['default']
    SubjectMode: typeof import('./src/components/ThemeConfig/components/SubjectMode.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
    ThemeConfig: typeof import('./src/components/ThemeConfig/index.vue')['default']
    Title: typeof import('./src/components/ThemeConfig/components/Title.vue')['default']
  }
}
