import {
  EditOutlined,
  TableRowsOutlined,
  TableChartTwotone,
  DynamicFeedOutlined,
  FormatAlignJustifyOutlined,
  FormatListNumberedFilled,
  NextPlanOutlined,
  PieChartOutlineTwotone,
  DriveFolderUploadOutlined,
  SettingsInputComponentOutlined,
  LocalPrintshopOutlined,
  ApiFilled,
  MapsHomeWorkRound,
  WorkFilled,
  AutoFixOffRound,
  HomeOutlined,
  HourglassBottomOutlined,
  HexagonOutlined,
} from '@vicons/material'
import { Component } from 'vue'

export const Icons: Record<string, Component> = {
  HomeOutlined,
  HexagonOutlined,
  TableRowsOutlined,
  TableChartTwotone,
  DynamicFeedOutlined,
  FormatAlignJustifyOutlined,
  FormatListNumberedFilled,
  NextPlanOutlined,
  EditOutlined,
  HourglassBottomOutlined,
  PieChartOutlineTwotone,
  DriveFolderUploadOutlined,
  ApiFilled,
  SettingsInputComponentOutlined,
  LocalPrintshopOutlined,
  MapsHomeWorkRound,
  WorkFilled,
  AutoFixOffRound,
}
