name: vue3-admin-templates CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.17.0'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy to production
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: main
        BRANCH: gh-pages
        FOLDER: build
